"""create classroom table

Revision ID: 153c7712ff1d
Revises: 
Create Date: 2023-04-22 21:08:24.473113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '153c7712ff1d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classrooms',
    sa.Column('classroom_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('building', sa.String(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('classroom_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('classrooms')
    # ### end Alembic commands ###
