"""init cascade relationships

Revision ID: adbe96599a1e
Revises: 692bdea5106b
Create Date: 2023-04-30 21:23:03.242239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adbe96599a1e'
down_revision = '692bdea5106b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('states', schema=None) as batch_op:
        batch_op.drop_constraint('states_class_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('states_classroom_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'classes', ['class_id'], ['class_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'classrooms', ['classroom_id'], ['classroom_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('states', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('states_classroom_id_fkey', 'classrooms', ['classroom_id'], ['classroom_id'])
        batch_op.create_foreign_key('states_class_id_fkey', 'classes', ['class_id'], ['class_id'])

    # ### end Alembic commands ###
